// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.943
package pages

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "awesomeProject1/internal/dto"
import "awesomeProject1/web/templates/components"

func RoomSettingsPage(room *dto.RoomResponse) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<div class=\"content\"><div class=\"section-title\">Room Settings</div><div class=\"settings-container\">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.RoomInfoSection(room.ID, *room).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.DangerZone(room.ID).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</div></div><script>\n\t\tdocument.addEventListener('click', function(e) {\n\t\t\tif (e.target.closest('.danger-btn')) {\n\t\t\t\tshowDialog(room.ID);\n\t\t\t}\n\t\t});\n\n\t\tfunction showDialog(id) {\n\t\t\tdocument.getElementById('dialog-' + id).style.display = 'flex';\n\t\t}\n\n\t\tfunction hideDialog(id) {\n\t\t\tdocument.getElementById('dialog-' + id).style.display = 'none';\n\t\t}\n\n\t\tfunction confirmAction(id) {\n\t\t\tfetch('/api/rooms/' + id, {\n\t\t\t\tmethod: 'DELETE',\n\t\t\t\theaders: {\n\t\t\t\t\t'Authorization': 'Bearer ' + localStorage.getItem('token') || document.cookie.split('token=')[1]?.split(';')[0] || ''\n\t\t\t\t}\n\t\t\t})\n\t\t\t.then(response => response.json())\n\t\t\t.then(data => {\n\t\t\t\tif (data.message) {\n\t\t\t\t\tshowToast('Room deleted successfully!', 'success');\n\t\t\t\t\tsetTimeout(() => {\n\t\t\t\t\t\twindow.location.href = '/';\n\t\t\t\t\t}, 1000);\n\t\t\t\t} else {\n\t\t\t\t\tshowToast('Error deleting room', 'error');\n\t\t\t\t}\n\t\t\t})\n\t\t\t.catch(error => {\n\t\t\t\tconsole.error('Error:', error);\n\t\t\t\tshowToast('Error deleting room', 'error');\n\t\t\t});\n\t\t}\n\t</script>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
